# Firewall rules for LiveKit WebRTC traffic

# Allow WebRTC media (UDP)
resource "google_compute_firewall" "livekit_webrtc_udp" {
  count = var.enable_livekit ? 1 : 0

  name    = "livekit-webrtc-udp"
  network = "default"
  project = var.project_id

  allow {
    protocol = "udp"
    ports    = ["50000-50200", "7882", "3478"]
  }

  source_ranges = ["0.0.0.0/0"]
  # Target the current GKE node pool nodes
  # This tag is generated by GKE and changes when the cluster is recreated
  target_tags = ["gke-dev-playground-46774c46-node"]

  description = "Allow LiveKit WebRTC UDP traffic to GKE nodes"
}

# Allow LiveKit HTTP/WebSocket and RTC TCP
resource "google_compute_firewall" "livekit_tcp" {
  count = var.enable_livekit ? 1 : 0

  name    = "livekit-tcp"
  network = "default"
  project = var.project_id

  allow {
    protocol = "tcp"
    ports    = ["80", "443", "7880", "7881", "5349"]
  }

  source_ranges = ["0.0.0.0/0"]
  # Target the current GKE node pool nodes
  # This tag is generated by GKE and changes when the cluster is recreated
  target_tags = ["gke-dev-playground-46774c46-node"]

  description = "Allow LiveKit HTTP/WebSocket and RTC TCP traffic to GKE nodes"
}


# Allow iperf3 testing to node
resource "google_compute_firewall" "livekit_iperf3_tcp_udp" {
  count = var.enable_livekit ? 1 : 0

  name    = "livekit-iperf3-tcp-udp"
  network = "default"
  project = var.project_id

  allow {
    protocol = "tcp"
    ports    = ["5201"]
  }

  allow {
    protocol = "udp"
    ports    = ["5201"]
  }

  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["gke-dev-playground-46774c46-node"]
  description   = "Allow iperf3 testing to node"
}
