apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chat-app
  labels:
    cloud.googleapis.com/location: europe-west4
  annotations:
    autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: BETA

spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1" # kpt-set: ${minScale}
        autoscaling.knative.dev/maxScale: "10" # kpt-set: ${maxScale}
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80 # kpt-set: ${containerConcurrency}
      serviceAccountName: REPLACEMENT # kpt-set: ${serviceAccountName}
      containers:
        - name: chat-app
          image: chat-app:latest
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            - name: REDIS_URL
              value: redis://10.89.162.227:6379
        - name: chat-app-auth
          image: chat-app-auth:latest
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
        - name: chat-app-frontend
          image: chat-app-frontend:latest
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

        - name: envoy-proxy
          image: envoyproxy/envoy:tools-dev
          args: ["--config-path", "/etc/envoy/config/envoy.yaml"]
          ports:
            - name: http1
              containerPort: 9000
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy/config

      volumes:
        - name: envoy-config
          secret:
            secretName: chat-app-envoy-config # kpt-set: ${envoy-config-secret-name}
            items:
              - key: "REPLACEMENT_VERSION" # kpt-set: ${envoy-config-secret-version}
                path: "envoy.yaml"

  traffic:
    - percent: 100
      latestRevision: true
