FROM python:3.11

WORKDIR /code


COPY ./auth_service/requirements.txt .
COPY ./auth_service/setup.py .


RUN pip install --no-cache-dir --upgrade -r requirements.txt \
    && pip install --no-cache-dir -e .


COPY ./auth_service .


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]