FROM python:3.9

WORKDIR /code


COPY ./chat-app/requirements.txt /code/requirements.txt


RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


COPY ./chat-app /code/app


CMD ["uvicorn", "app.auth_service:app", "--host", "0.0.0.0", "--port", "8001"]