apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: auth-service
  labels:
    cloud.googleapis.com/location: europe-west4
  annotations:
    autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: BETA

spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1" # kpt-set: ${minScale}
        autoscaling.knative.dev/maxScale: "10" # kpt-set: ${maxScale}
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80 # kpt-set: ${containerConcurrency}
      serviceAccountName: REPLACEMENT # kpt-set: ${serviceAccountName}
      containers:
        - name: auth-service
          image: auth-service:latest
          ports:
            - name: http1
              containerPort: 8001
          startupProbe:
            tcpSocket:
              port: 8001
            timeoutSeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

  traffic:
    - percent: 100
      latestRevision: true
